version: "2"

services:
  web:
    build: ./nodejs
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=3032
    ports:
      - "3032"
    command: npm start

  nginx:
    build: ./nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    links:
      - web:web
